name = "cuellar-photography-local"
compatibility_date = "2026-08-18"

[[d1_databases]]
binding = "DB"
database_name = "cuellar-photography-local"
database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "database/migrations"