import type { Gallery, Photo } from '../types/content';

export const categories = [
  'Paisaje',
  'Naturaleza',
  'Fauna',
  'Macro',
  'Nocturna',
  'Astrofotografía',
  'Fotografía creativa',
  'IA',
  'Retratos',
  'Creaciones con IA',
] as const;

export const galleries: Gallery[] = [
  {
    id: 'gallery-landscape',
    slug: 'horizontes-abiertos',
    title: 'Paisaje',
    description: 'Luz, relieve y horizontes abiertos. Selección visual provisional.',
    category: 'Paisaje',
    coverPhotoSlug: 'luz-en-el-valle',
  },
  {
    id: 'gallery-nature',
    slug: 'materia-viva',
    title: 'Naturaleza',
    description: 'Formas, ritmos y materia en el entorno natural. Selección visual provisional.',
    category: 'Naturaleza',
    coverPhotoSlug: 'silencio-vegetal',
  },
  {
    id: 'gallery-wildlife',
    slug: 'encuentros-silvestres',
    title: 'Fauna',
    description: 'Presencias discretas y encuentros en libertad. Selección visual provisional.',
    category: 'Fauna',
    coverPhotoSlug: 'el-vigia-de-la-roca',
  },
  {
    id: 'gallery-macro',
    slug: 'vida-en-detalle',
    title: 'Macro',
    description: 'Textura, patrón y escala en los detalles que pasan inadvertidos. Selección visual provisional.',
    category: 'Macro',
    coverPhotoSlug: 'geometria-organica',
  },
  {
    id: 'gallery-night',
    slug: 'despues-del-sol',
    title: 'Nocturna',
    description: 'Tiempo lento, sombra y luz residual. Selección visual provisional.',
    category: 'Nocturna',
    coverPhotoSlug: 'linea-de-noche',
  },
  {
    id: 'gallery-astro',
    slug: 'cielo-profundo',
    title: 'Astrofotografía',
    description: 'La escala del cielo nocturno en una selección visual provisional.',
    category: 'Astrofotografía',
    coverPhotoSlug: 'trazo-celeste',
  },
  {
    id: 'gallery-creative',
    slug: 'realidad-recompuesta',
    title: 'Fotografía creativa',
    description: 'Interpretaciones visuales donde la imagen propone otro lugar. Selección visual provisional.',
    category: 'Fotografía creativa',
    coverPhotoSlug: 'campo-imaginado',
  },
  {
    id: 'gallery-ai',
    slug: 'imagenes-sinteticas',
    title: 'IA',
    description: 'Exploraciones visuales generadas como parte de un archivo en evolución.',
    category: 'IA',
    coverPhotoSlug: 'forma-sintetica',
  },
  {
    id: 'gallery-portraits',
    slug: 'retratos',
    title: 'Retratos',
    description: 'Presencia, gesto y luz en una selección visual provisional.',
    category: 'Retratos',
    coverPhotoSlug: 'presencia-retratada',
  },
  {
    id: 'gallery-ai-creations',
    slug: 'creaciones-ia',
    title: 'Creaciones con IA',
    description: 'Imágenes creadas con inteligencia artificial como parte de un archivo en evolución.',
    category: 'Creaciones con IA',
    coverPhotoSlug: 'escena-generada',
  },
];

export const photos: Photo[] = [
  {
    id: 'photo-landscape-light',
    slug: 'luz-en-el-valle',
    title: 'Luz en el valle',
    description: 'Estudio provisional de la luz sobre un paisaje abierto.',
    alt: 'Placeholder identificado para una fotografía de paisaje.',
    gallerySlug: 'horizontes-abiertos',
    category: 'Paisaje',
    image: '/images/placeholders/landscape-detail.svg',
    thumbnail: '/images/placeholders/landscape-card.svg',
    width: 1600,
    height: 1067,
  },
  {
    id: 'photo-nature-stillness',
    slug: 'silencio-vegetal',
    title: 'Silencio vegetal',
    description: 'Estudio provisional de formas vegetales y luz filtrada.',
    alt: 'Placeholder identificado para una fotografía de naturaleza.',
    gallerySlug: 'materia-viva',
    category: 'Naturaleza',
    image: '/images/placeholders/nature-detail.svg',
    thumbnail: '/images/placeholders/nature-card.svg',
    width: 1600,
    height: 1067,
  },
  {
    id: 'photo-macro-geometry',
    slug: 'geometria-organica',
    title: 'Geometría orgánica',
    description: 'Estudio provisional de estructuras orgánicas a escala cercana.',
    alt: 'Placeholder identificado para una fotografía macro.',
    gallerySlug: 'vida-en-detalle',
    category: 'Macro',
    image: '/images/placeholders/macro-detail.svg',
    thumbnail: '/images/placeholders/macro-card.svg',
    width: 1200,
    height: 1500,
  },
  {
    id: 'photo-fauna-vigia-roca',
    slug: 'el-vigia-de-la-roca',
    title: 'El vigía de la roca',
    description: 'Buitre posado entre las rocas, observado en libertad bajo una luz cálida de atardecer.',
    alt: 'Buitre posado entre rocas en un paisaje natural.',
    gallerySlug: 'encuentros-silvestres',
    category: 'Fauna',
    image: '/images/Fauna/buitre-en-la-roca.jpg',
    thumbnail: '/images/Fauna/buitre-en-la-roca.jpg',
    width: 1600,
    height: 1067,
  },
  {
    id: 'photo-night-line',
    slug: 'linea-de-noche',
    title: 'Línea de noche',
    description: 'Estudio provisional de profundidad, oscuridad y luz nocturna.',
    alt: 'Placeholder identificado para una fotografía nocturna.',
    gallerySlug: 'despues-del-sol',
    category: 'Nocturna',
    image: '/images/placeholders/night-detail.svg',
    thumbnail: '/images/placeholders/night-card.svg',
    width: 1600,
    height: 1067,
  },
  {
    id: 'photo-creative-field',
    slug: 'campo-imaginado',
    title: 'Campo imaginado',
    description: 'Estudio provisional de composición e imagen transformada.',
    alt: 'Placeholder identificado para una fotografía creativa.',
    gallerySlug: 'realidad-recompuesta',
    category: 'Fotografía creativa',
    image: '/images/placeholders/creative-detail.svg',
    thumbnail: '/images/placeholders/creative-card.svg',
    width: 1600,
    height: 1067,
  },
  {
    id: 'photo-astro-trace',
    slug: 'trazo-celeste',
    title: 'Trazo celeste',
    description: 'Estudio provisional del movimiento y la escala del cielo nocturno.',
    alt: 'Placeholder identificado para una fotografía de astrofotografía.',
    gallerySlug: 'cielo-profundo',
    category: 'Astrofotografía',
    image: '/images/Astrofotografia/luna-de-ayer.jpg',
    thumbnail: '/images/Astrofotografia/luna-de-ayer.jpg',
    width: 1600,
    height: 1067,
  },
  {
    id: 'photo-ai-form',
    slug: 'forma-sintetica',
    title: 'Forma sintética',
    description: 'Exploración visual provisional creada con herramientas de IA.',
    alt: 'Placeholder identificado para una imagen creada con inteligencia artificial.',
    gallerySlug: 'imagenes-sinteticas',
    category: 'IA',
    image: '/images/placeholders/creative-detail.svg',
    thumbnail: '/images/placeholders/creative-card.svg',
    width: 1600,
    height: 1067,
  },
  {
    id: 'photo-portrait-presence',
    slug: 'presencia-retratada',
    title: 'Presencia retratada',
    description: 'Estudio provisional de un retrato, su luz y su presencia.',
    alt: 'Placeholder identificado para una fotografía de retrato.',
    gallerySlug: 'retratos',
    category: 'Retratos',
    image: '/images/placeholders/wildlife-detail.svg',
    thumbnail: '/images/placeholders/wildlife-card.svg',
    width: 1200,
    height: 1500,
  },
  {
    id: 'photo-ai-scene',
    slug: 'escena-generada',
    title: 'Escena generada',
    description: 'Exploración visual provisional creada con herramientas de inteligencia artificial.',
    alt: 'Placeholder identificado para una creación visual con inteligencia artificial.',
    gallerySlug: 'creaciones-ia',
    category: 'Creaciones con IA',
    image: '/images/placeholders/creative-detail.svg',
    thumbnail: '/images/placeholders/creative-card.svg',
    width: 1600,
    height: 1067,
  },
];

export function getGallery(slug: string) {
  return galleries.find((gallery) => gallery.slug === slug);
}

export function getPhoto(slug: string) {
  return photos.find((photo) => photo.slug === slug);
}

export function getGalleryPhotos(gallerySlug: string) {
  return photos.filter((photo) => photo.gallerySlug === gallerySlug);
}
